import { FoodItem } from "@/types";

export const foodItems: FoodItem[] = [
  {
  id: "101",
  name: "Paneer Butter Masala",
  description:
    "Soft paneer cubes cooked in a rich creamy tomato-based gravy.",
  category: "Veg",
  cuisine: "Indian",
  spiceLevel: "Medium",
  tags: ["Creamy", "Popular"],
  price: 249,
  image:
    "https://images.unsplash.com/photo-1631452180519-c014fe946bc7",
},

{
  id: "102",
  name: "Chicken Burger",
  description:
    "Juicy chicken patty burger layered with fresh lettuce and sauces.",
  category: "Non-Veg",
  cuisine: "American",
  spiceLevel: "Mild",
  tags: ["Fast Food"],
  price: 199,
  image:
    "https://images.unsplash.com/photo-1568901346375-23c9450c58cd",
},

{
  id: "103",
  name: "Veg Pizza",
  description:
    "Classic pizza topped with fresh vegetables and melted cheese.",
  category: "Veg",
  cuisine: "Italian",
  spiceLevel: "Mild",
  tags: ["Cheesy", "Kids"],
  price: 299,
  image:
    "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3",
},

{
  id: "104",
  name: "Chicken Biryani",
  description:
    "Aromatic basmati rice layered with spicy chicken and herbs.",
  category: "Non-Veg",
  cuisine: "Indian",
  spiceLevel: "Spicy",
  tags: ["Popular", "Rice"],
  price: 349,
  image:
    "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a",
},

{
  id: "105",
  name: "Hakka Noodles",
  description:
    "Stir-fried noodles tossed with vegetables and Chinese sauces.",
  category: "Veg",
  cuisine: "Chinese",
  spiceLevel: "Medium",
  tags: ["Noodles"],
  price: 229,
  image:
    "https://images.unsplash.com/photo-1617622141573-1d6f4f0d6b6b",
},

{
  id: "106",
  name: "Spicy Chicken Wings",
  description:
    "Crispy chicken wings coated in a fiery spicy glaze.",
  category: "Non-Veg",
  cuisine: "American",
  spiceLevel: "Spicy",
  tags: ["Fast Food", "Popular"],
  price: 279,
  image:
    "https://images.unsplash.com/photo-1608039829572-78524f79c4c7",
},

  {
  id: "107",
  name: "Dal Makhani",
  description:
    "Slow-cooked black lentils simmered in a rich buttery gravy.",
  category: "Veg",
  cuisine: "Indian",
  spiceLevel: "Mild",
  tags: ["Creamy", "Comfort Food", "Popular"],
  price: 229,
  image:
    "https://images.unsplash.com/photo-1546833999-b9f581a1996d",
},

{
  id: "108",
  name: "Palak Paneer",
  description:
    "Soft paneer cubes cooked in a nutritious spinach-based gravy.",
  category: "Veg",
  cuisine: "Indian",
  spiceLevel: "Medium",
  tags: ["Healthy", "Paneer", "Protein"],
  price: 259,
  image:
    "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4",
},

{
  id: "109",
  name: "Chole Bhature",
  description:
    "Spicy chickpea curry served with fluffy deep-fried bhature.",
  category: "Veg",
  cuisine: "Indian",
  spiceLevel: "Medium",
  tags: ["Street Food", "Popular"],
  price: 239,
  image:
    "https://images.unsplash.com/photo-1565557623262-b51c2513a641",
},

{
  id: "110",
  name: "Malai Kofta",
  description:
    "Soft paneer and potato dumplings in a creamy tomato gravy.",
  category: "Veg",
  cuisine: "Indian",
  spiceLevel: "Mild",
  tags: ["Creamy", "Premium"],
  price: 269,
  image:
    "https://images.unsplash.com/photo-1585937421612-70a008356fbe",
},

{
  id: "111",
  name: "Veg Pulao",
  description:
    "Fragrant basmati rice cooked with vegetables and mild spices.",
  category: "Veg",
  cuisine: "Indian",
  spiceLevel: "Mild",
  tags: ["Rice", "Healthy"],
  price: 219,
  image:
    "https://images.unsplash.com/photo-1512058564366-18510be2db19",
},

{
  id: "112",
  name: "Butter Chicken",
  description:
    "Tender chicken pieces cooked in a creamy tomato butter sauce.",
  category: "Non-Veg",
  cuisine: "Indian",
  spiceLevel: "Medium",
  tags: ["Popular", "Creamy", "Premium"],
  price: 329,
  image:
    "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398",
},

{
  id: "113",
  name: "Chicken Tikka",
  description:
    "Juicy chicken cubes marinated in spices and grilled to perfection.",
  category: "Non-Veg",
  cuisine: "Indian",
  spiceLevel: "Spicy",
  tags: ["Grilled", "High Protein"],
  price: 299,
  image:
    "https://images.unsplash.com/photo-1596797038530-2c107aaab6c5",
},

{
  id: "114",
  name: "Tandoori Chicken",
  description:
    "Traditional clay-oven roasted chicken infused with Indian spices.",
  category: "Non-Veg",
  cuisine: "Indian",
  spiceLevel: "Spicy",
  tags: ["Popular", "Grilled"],
  price: 349,
  image:
    "https://images.unsplash.com/photo-1527477396000-e27163b481c2",
},

{
  id: "115",
  name: "Mutton Rogan Josh",
  description:
    "Tender mutton slow-cooked in aromatic Kashmiri spices.",
  category: "Non-Veg",
  cuisine: "Indian",
  spiceLevel: "Spicy",
  tags: ["Premium", "Rich"],
  price: 399,
  image:
    "https://images.unsplash.com/photo-1544025162-d76694265947",
},

{
  id: "116",
  name: "Fish Curry",
  description:
    "Fresh fish cooked in a tangy coastal-style curry.",
  category: "Non-Veg",
  cuisine: "Indian",
  spiceLevel: "Medium",
  tags: ["Seafood", "Protein"],
  price: 359,
  image:
    "https://images.unsplash.com/photo-1559847844-d721426d6edc",
},
  {
  id: "117",
  name: "Veg Fried Rice",
  description: "Wok-tossed rice with fresh vegetables and soy sauce.",
  category: "Veg",
  cuisine: "Chinese",
  spiceLevel: "Mild",
  tags: ["Rice", "Healthy"],
  price: 219,
  image: "https://images.unsplash.com/photo-1512058564366-18510be2db19",
},
{
  id: "118",
  name: "Veg Manchurian",
  description: "Crispy vegetable balls tossed in Indo-Chinese sauce.",
  category: "Veg",
  cuisine: "Chinese",
  spiceLevel: "Medium",
  tags: ["Popular", "Street Food"],
  price: 239,
  image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4",
},
{
  id: "119",
  name: "Spring Rolls",
  description: "Crispy rolls stuffed with seasoned vegetables.",
  category: "Veg",
  cuisine: "Chinese",
  spiceLevel: "Mild",
  tags: ["Snacks", "Crispy"],
  price: 189,
  image: "https://images.unsplash.com/photo-1544025162-d76694265947",
},
{
  id: "120",
  name: "Schezwan Noodles",
  description: "Spicy noodles tossed with vegetables and Schezwan sauce.",
  category: "Veg",
  cuisine: "Chinese",
  spiceLevel: "Spicy",
  tags: ["Noodles", "Spicy"],
  price: 249,
  image: "https://images.unsplash.com/photo-1617622141573-1d6f4f0d6b6b",
},
{
  id: "121",
  name: "Chicken Fried Rice",
  description: "Classic fried rice loaded with chicken and vegetables.",
  category: "Non-Veg",
  cuisine: "Chinese",
  spiceLevel: "Mild",
  tags: ["Rice", "Protein"],
  price: 269,
  image: "https://images.unsplash.com/photo-1604908176997-431fa7d65c74",
},
{
  id: "122",
  name: "Chicken Manchurian",
  description: "Fried chicken tossed in a spicy Indo-Chinese sauce.",
  category: "Non-Veg",
  cuisine: "Chinese",
  spiceLevel: "Medium",
  tags: ["Popular", "Protein"],
  price: 289,
  image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b",
},
{
  id: "123",
  name: "Schezwan Chicken",
  description: "Spicy chicken stir-fried with peppers and Schezwan sauce.",
  category: "Non-Veg",
  cuisine: "Chinese",
  spiceLevel: "Spicy",
  tags: ["Spicy", "Protein"],
  price: 309,
  image: "https://images.unsplash.com/photo-1527477396000-e27163b481c2",
},
{
  id: "124",
  name: "Chicken Noodles",
  description: "Stir-fried noodles with juicy chicken strips.",
  category: "Non-Veg",
  cuisine: "Chinese",
  spiceLevel: "Medium",
  tags: ["Noodles", "Protein"],
  price: 279,
  image: "https://images.unsplash.com/photo-1585032226651-759b368d7246",
},
{
  id: "125",
  name: "Chilli Chicken",
  description: "Crispy chicken tossed in spicy chilli sauce.",
  category: "Non-Veg",
  cuisine: "Chinese",
  spiceLevel: "Spicy",
  tags: ["Popular", "Spicy"],
  price: 299,
  image: "https://images.unsplash.com/photo-1559847844-d721426d6edc",
},

{
  id: "126",
  name: "Margherita Pizza",
  description: "Classic pizza with mozzarella, basil and tomato sauce.",
  category: "Veg",
  cuisine: "Italian",
  spiceLevel: "Mild",
  tags: ["Cheesy", "Popular"],
  price: 289,
  image: "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3",
},
{
  id: "127",
  name: "Pasta Alfredo",
  description: "Creamy white sauce pasta topped with herbs.",
  category: "Veg",
  cuisine: "Italian",
  spiceLevel: "Mild",
  tags: ["Creamy", "Comfort Food"],
  price: 269,
  image: "https://images.unsplash.com/photo-1645112411341-6c4fd023882c",
},
{
  id: "128",
  name: "Lasagna",
  description: "Layered pasta baked with rich tomato sauce and cheese.",
  category: "Veg",
  cuisine: "Italian",
  spiceLevel: "Medium",
  tags: ["Premium", "Cheesy"],
  price: 329,
  image: "https://images.unsplash.com/photo-1619895092538-128341789043",
},
{
  id: "129",
  name: "Mushroom Risotto",
  description: "Creamy Italian rice dish cooked with mushrooms.",
  category: "Veg",
  cuisine: "Italian",
  spiceLevel: "Mild",
  tags: ["Premium", "Rice"],
  price: 319,
  image: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601",
},
{
  id: "130",
  name: "Four Cheese Pizza",
  description: "Pizza loaded with four types of premium cheese.",
  category: "Veg",
  cuisine: "Italian",
  spiceLevel: "Mild",
  tags: ["Cheesy", "Premium"],
  price: 349,
  image: "https://images.unsplash.com/photo-1513104890138-7c749659a591",
},
{
  id: "131",
  name: "Chicken Pizza",
  description: "Loaded pizza topped with seasoned chicken chunks.",
  category: "Non-Veg",
  cuisine: "Italian",
  spiceLevel: "Medium",
  tags: ["Cheesy", "Protein"],
  price: 369,
  image: "https://images.unsplash.com/photo-1513104890138-7c749659a591",
},
{
  id: "132",
  name: "Chicken Alfredo Pasta",
  description: "Creamy Alfredo pasta with grilled chicken.",
  category: "Non-Veg",
  cuisine: "Italian",
  spiceLevel: "Mild",
  tags: ["Creamy", "Protein"],
  price: 339,
  image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9",
},
{
  id: "133",
  name: "Pepperoni Pizza",
  description: "Italian pizza topped with pepperoni slices.",
  category: "Non-Veg",
  cuisine: "Italian",
  spiceLevel: "Medium",
  tags: ["Popular", "Premium"],
  price: 389,
  image: "https://images.unsplash.com/photo-1513104890138-7c749659a591",
},
{
  id: "134",
  name: "Chicken Lasagna",
  description: "Classic lasagna layered with chicken and cheese.",
  category: "Non-Veg",
  cuisine: "Italian",
  spiceLevel: "Medium",
  tags: ["Premium", "Protein"],
  price: 359,
  image: "https://images.unsplash.com/photo-1619895092538-128341789043",
},
{
  id: "135",
  name: "Chicken Risotto",
  description: "Creamy risotto topped with grilled chicken.",
  category: "Non-Veg",
  cuisine: "Italian",
  spiceLevel: "Mild",
  tags: ["Rice", "Premium"],
  price: 349,
  image: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601",
},

{
  id: "136",
  name: "Veg Burger",
  description: "Grilled veggie patty burger with fresh lettuce.",
  category: "Veg",
  cuisine: "American",
  spiceLevel: "Mild",
  tags: ["Fast Food", "Popular"],
  price: 179,
  image: "https://images.unsplash.com/photo-1550547660-d9450f859349",
},
{
  id: "137",
  name: "Loaded Fries",
  description: "French fries loaded with cheese and sauces.",
  category: "Veg",
  cuisine: "American",
  spiceLevel: "Medium",
  tags: ["Snacks", "Cheesy"],
  price: 169,
  image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877",
},
{
  id: "138",
  name: "Mac & Cheese",
  description: "Creamy macaroni loaded with melted cheese.",
  category: "Veg",
  cuisine: "American",
  spiceLevel: "Mild",
  tags: ["Comfort Food", "Cheesy"],
  price: 229,
  image: "https://images.unsplash.com/photo-1543332164-6e82f355badc",
},
{
  id: "139",
  name: "Veg Hot Dog",
  description: "Vegetarian hot dog loaded with sauces and veggies.",
  category: "Veg",
  cuisine: "American",
  spiceLevel: "Medium",
  tags: ["Fast Food"],
  price: 189,
  image: "https://images.unsplash.com/photo-1612392062798-09ff5b08d9ba",
},
{
  id: "140",
  name: "Cheeseburger",
  description: "Juicy beef-style burger topped with cheese.",
  category: "Non-Veg",
  cuisine: "American",
  spiceLevel: "Mild",
  tags: ["Popular", "Cheesy"],
  price: 249,
  image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd",
},
{
  id: "141",
  name: "BBQ Chicken Burger",
  description: "Chicken burger glazed with smoky BBQ sauce.",
  category: "Non-Veg",
  cuisine: "American",
  spiceLevel: "Medium",
  tags: ["Fast Food", "Protein"],
  price: 269,
  image: "https://images.unsplash.com/photo-1550547660-d9450f859349",
},
{
  id: "142",
  name: "Hot Dog",
  description: "Classic American hot dog with mustard and ketchup.",
  category: "Non-Veg",
  cuisine: "American",
  spiceLevel: "Mild",
  tags: ["Street Food", "Fast Food"],
  price: 199,
  image: "https://images.unsplash.com/photo-1612392062798-09ff5b08d9ba",
},
{
  id: "143",
  name: "Veg Tacos",
  description: "Soft tacos filled with vegetables and salsa.",
  category: "Veg",
  cuisine: "Mexican",
  spiceLevel: "Medium",
  tags: ["Street Food", "Healthy"],
  price: 219,
  image: "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85",
},
{
  id: "144",
  name: "Veg Burrito",
  description: "Flour tortilla packed with beans, rice and vegetables.",
  category: "Veg",
  cuisine: "Mexican",
  spiceLevel: "Medium",
  tags: ["Rice", "Healthy"],
  price: 239,
  image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f",
},
{
  id: "145",
  name: "Nachos",
  description: "Crispy tortilla chips served with salsa and cheese.",
  category: "Veg",
  cuisine: "Mexican",
  spiceLevel: "Mild",
  tags: ["Snacks", "Cheesy"],
  price: 199,
  image: "https://images.unsplash.com/photo-1513456852971-30c0b8199d4d",
},
{
  id: "146",
  name: "Quesadilla",
  description: "Grilled tortilla filled with melted cheese and veggies.",
  category: "Veg",
  cuisine: "Mexican",
  spiceLevel: "Mild",
  tags: ["Cheesy", "Popular"],
  price: 249,
  image: "https://images.unsplash.com/photo-1599974579688-8dbdd335c77f",
},
{
  id: "147",
  name: "Chicken Tacos",
  description: "Mexican tacos stuffed with seasoned chicken.",
  category: "Non-Veg",
  cuisine: "Mexican",
  spiceLevel: "Medium",
  tags: ["Protein", "Popular"],
  price: 269,
  image: "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85",
},
{
  id: "148",
  name: "Chicken Burrito",
  description: "Large tortilla wrap filled with chicken and rice.",
  category: "Non-Veg",
  cuisine: "Mexican",
  spiceLevel: "Medium",
  tags: ["Rice", "Protein"],
  price: 289,
  image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f",
},
{
  id: "149",
  name: "Chicken Quesadilla",
  description: "Grilled tortilla packed with cheese and chicken.",
  category: "Non-Veg",
  cuisine: "Mexican",
  spiceLevel: "Medium",
  tags: ["Cheesy", "Protein"],
  price: 299,
  image: "https://images.unsplash.com/photo-1599974579688-8dbdd335c77f",
},
{
  id: "150",
  name: "Loaded Chicken Nachos",
  description: "Nachos loaded with chicken, cheese and salsa.",
  category: "Non-Veg",
  cuisine: "Mexican",
  spiceLevel: "Spicy",
  tags: ["Popular", "Cheesy"],
  price: 319,
  image: "https://images.unsplash.com/photo-1513456852971-30c0b8199d4d",
},
{
  id: "151",
  name: "Chicken Fajitas",
  description: "Sizzling grilled chicken served with tortillas.",
  category: "Non-Veg",
  cuisine: "Mexican",
  spiceLevel: "Spicy",
  tags: ["Protein", "Premium"],
  price: 339,
  image: "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85",
},
];